apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-demo
  labels:
    app: ecommerce-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-demo
  template:
    metadata:
      labels:
        app: ecommerce-demo
    spec:
      containers:
      - name: ecommerce-demo
        image: weaveworksdemos/front-end:0.3.12
        ports:
        - containerPort: 8079
